### ISSUE TITLE
Helm template command

### ISSUE THREAD

**Issue by rasros** [manusa/helm-java#105]
Please consider implementing the `helm template` command. The current install in helm-java with dry-run option does not include the MANIFEST field for some reason so it is not a substitute for template.

**Comment by manusa** [comment]
I've just published v0.0.11 with the requested changes on this issue that were contributed by @lotharking:

- https://repo1.maven.org/maven2/com/marcnuri/helm-java/helm-java/0.0.11/
- https://github.com/manusa/helm-java/releases/tag/v0.0.11

Please, share any feedback you may have, it is much appreciated
