### ISSUE TITLE
Helm upgrade command not working

### ISSUE THREAD

**Issue by sachinkaushik** [manusa/helm-java#125]
I have a helm chart that have two deployments(grafana and hello-world) , I want to update image of deployment grafana.

I was trying using below code, but some how its trying to connect to kubernetes cluster.

 UpgradeCommand upgrade = new Helm(Paths.get("/data/my-helm-chart")).upgrade();
        upgrade.set("grafana.image.repository", "grafana/grafana-new:latest").call();
        

Can you please help with correct code. If I have to update any content(name, image, etc) of any deployments in the helm chart.
How can I do it using helm.upgrade()

**Comment by manusa** [comment]
> I was trying using below code, but some how its trying to connect to kubernetes cluster.

The helm upgrade command will upgrade the chart in your cluster. It **requires** a Kubernetes Cluster configuration.

Your code looks correct to me.

**Comment by sachinkaushik** [comment]
@manusa Is there any code that can be used to update helm chart file only.. ?

**Comment by manusa** [comment]
> @manusa Is there any way/code that can be used to update helm chart file only.. ?

You can try the fabric8 Kubernetes Client for that purpose and others:
https://github.com/fabric8io/kubernetes-client
