### ISSUE TITLE
Java Helm install with token 

### ISSUE THREAD

**Issue by vkanaparthy** [manusa/helm-java#146]
I want to install opensearch helm chart from docker container. The docker container has aws access key and secret. 

I can obtain a token from the approach here, https://github.com/aws/aws-sdk-java/issues/1795.

How do i pass the token to the Java Helm?

Appreciate any thoughts?

**Comment by manusa** [comment]
In general, the same way you'd pass the token to the Helm CLI tool.

**Comment by vkanaparthy** [comment]
Closing the issue. I am creating kubeconfig from eks cluster in docker container.
