### ISSUE TITLE
Timeout option missing for install

### ISSUE THREAD

**Issue by leforthomas** [manusa/helm-java#170]
I could not find a timeout in the install options. I have a chart that can be quite time consuming to deploy, at least the first time. It fails to install after 5mns more or less with the deadline exceeded error. This seems to be the default value. Maybe I missed a parameter in the doc/code? if not it would be nice to have it as an option, as per https://helm.sh/docs/helm/helm_install/

Thanks for creating this lib, very useful!

**Comment by manusa** [comment]
Sorry for the late reply.
There is no timeout option yet, it seems I overlooked it when I implemented the install command.
I'll add it soon.

**Comment by manusa** [comment]
I've just published v0.0.13 which includes the feature requested in this issue:

    https://repo1.maven.org/maven2/com/marcnuri/helm-java/helm-java/0.0.13/
    https://github.com/manusa/helm-java/releases/tag/v0.0.13

Please, share any feedback you may have, it is much appreciated 🙏
