### ISSUE TITLE
Template namespace option

### ISSUE THREAD

**Issue by rasros** [manusa/helm-java#187]
The template command is missing the namespace option. Thanks for implementing the template command btw.

**Comment by manusa** [comment]
I've just published v0.0.12 which includes the feature requested in this issue:

- https://repo1.maven.org/maven2/com/marcnuri/helm-java/helm-java/0.0.12/
- https://github.com/manusa/helm-java/releases/tag/v0.0.12

Please, share any feedback you may have, it is much appreciated :pray:
