### ISSUE TITLE
Don't you support the oci

### ISSUE THREAD

**Issue by swlee90** [manusa/helm-java#189]
When installing, it seems to be installed only when the repo is registered. 

Please support it to be installed as an oci.

**Comment by manusa** [comment]
Hi @swlee90 
I don't understand what you're describing, could you please elaborate?
Maybe you can also include the commands that work with the helm binary that don't work with this library.

**Comment by swlee90** [comment]
@manusa My question was whether it is difficult to install a Helm chart using the OCI registry method.

**Comment by manusa** [comment]
Do you mean something like this?

```java
// Add a repo with the OCI charts
Helm.repo().add()
  .withUrl(URI.create("https://charts.helm.sh/stable"))
  .withName("repo-name")
  .call();
// Install a chart from that repo
Helm.install("repo-name/ingress-nginx").call();
```

> My question was whether it is difficult to install a Helm chart using the OCI registry method.

As I said in the previous comment, please state what commands would you actually run using the standard `helm` CLI binary in your terminal.

**Comment by swlee90** [comment]
@manusa 
When I used `Helm.install("oci://registry-1.docker.io/bitnamicharts/postgresql").call(),` 

it didn’t work at first, so I thought OCI registry wasn't supported. However, after testing again, it’s working fine now. Thank you so much for replying to my answer.
