### ISSUE TITLE
Atomic option missing for install

### ISSUE THREAD

**Issue by miriSch** [manusa/helm-java#191]
I would like to use this library in our project since I am very happy using Fabric8 Kubernetes Client already (Thank you for also providing a library for helm!). However, for our usecase some options are missing, like `--timeout` (https://github.com/manusa/helm-java/issues/170) and also the `--atomic` option for `helm install` (https://helm.sh/docs/helm/helm_install/#options). For `helm upgrade` you already provide the `--atomic` option (https://github.com/manusa/helm-java/blob/main/helm-java/src/main/java/com/marcnuri/helm/UpgradeCommand.java#L40). Is there a reason for not providing it in [InstallCommand](https://github.com/manusa/helm-java/blob/main/helm-java/src/main/java/com/marcnuri/helm/InstallCommand.java)? Is there a plan to add the `atomic` option to `install` or must we workaround using `upgrade` with `--atomic` and `--install` options?

**Comment by manusa** [comment]
> Is there a reason for not providing it in [InstallCommand](https://github.com/manusa/helm-java/blob/main/helm-java/src/main/java/com/marcnuri/helm/InstallCommand.java)? Is there a plan to add the `atomic` option to `install` or must we workaround using `upgrade` with `--atomic` and `--install` options?

No reason.
I probably didn't do it at the time because implementing a test for that was difficult and when the install command was bootstrapped it was still a prototype.

I saw you already opened a PR with a fix, thanks :raised_hands: 

I'll try to merge and release soon.

**Comment by manusa** [comment]
I've just published v0.0.12 which includes the feature requested in this issue:

- https://repo1.maven.org/maven2/com/marcnuri/helm-java/helm-java/0.0.12/
- https://github.com/manusa/helm-java/releases/tag/v0.0.12

Please, share any feedback you may have, it is much appreciated :pray:
