### ISSUE TITLE
Command: helm search repo [repo_name], how to implement it

### ISSUE THREAD

**Issue by yx5411** [manusa/helm-java#87]

**Comment by manusa** [comment]
The `helm search` commands have not been implemente yet.

Are you using this library already?
If so, could you please share some details about your use cases?

**Comment by yx5411** [comment]
Yes, I am using this library and currently have a requirement:
1. command: helm repo list, I want to get all the repo information through this command first
2. command: helm search repo [repo_name], and then obtain all chart information under the specified repo

Note: This library is very good, because I have been looking for it for a long time recently, but I have not found any effective Java-related API to operate helm. Until I saw this project, I hope it can continue to be updated completely.

**Comment by manusa** [comment]
Awesome news!

The `helm repo list` is already available: https://github.com/manusa/helm-java?tab=readme-ov-file#repo-list

The other one I'll try to prioritize and find some time to implement it. Knowing that there's someone interested is always a good motivation :)

**Comment by Kyefer** [comment]
I am also interested in the ability to search Helm repos via this Java library.

I am building scripts via maven that upload Helm charts to a library so I would like to use Java to validate that the chart is present in the repo.

**Comment by manusa** [comment]
I just released https://github.com/manusa/helm-java/releases/tag/v0.0.7 with this feature.

Please, share any feedback you may have, it is much appreciated.
