### ISSUE TITLE
Unable to provide version or plain http settings in helm show command

### ISSUE THREAD

**Issue by Kyefer** [manusa/helm-java#94]
I am currently building Java tests to verify that a script uploads a Helm chart. I previously wanted to use the `helm search` command to do so. However, I am using an OCI compliant container (i.e. the [registry container](https://hub.docker.com/_/registry)) which supports pushing but is not a true Helm repo, so the repo and search commands do not work with it. However, according to the [Helm OCI-based registry documentation](https://helm.sh/docs/topics/registries/), the `helm show` command can function with it, so I am interested in using it as the method to validate the upload. However, to do this via the helm CLI, the --plain-http flag needs to be set, as well as setting the version via the --version argument. This API does not allow for those settings to be configured.

**Comment by Kyefer** [comment]
Please also note that to do this via the `helm` CLI, the `--plain-http` flag needs to be set, as well as setting the version via the `--version` argument.

**Comment by manusa** [comment]
I can try to add the additional options to the current [helm show](https://github.com/manusa/helm-java#show) implementation.

In any case, for your use case, you might be better off using a plain HTTP client and retrieving the information manually. You can check the API here: https://specs.opencontainers.org/distribution-spec/?v=v1.0.0#endpoints

**Comment by Kyefer** [comment]
Hi @manusa, I see that this functionality was added to the library. I am eager to try it out. Would you be able to release a new version with this feature? Thanks

**Comment by manusa** [comment]
I've just published v0.0.8 with the requested changes on this issue:
- https://repo1.maven.org/maven2/com/marcnuri/helm-java/helm-java/0.0.8/
- https://github.com/manusa/helm-java/releases/tag/v0.0.8

Please, provide feedback.
